name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: read-all

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: rhysd/actionlint@b7e9dbb4bfe1df65a1bca617e68640f68f218d08 # v1.7.7
