name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: read-all

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
        with:
          args: -shellcheck ""
