name: Add Help Wanted Label

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  label:
    uses: kubestellar/infra/.github/workflows/reusable-add-help-wanted.yml@9a15d65135864435badfb9293251e8701b562899  # main
    secrets: inherit
