name: Assignment Helper

on:
  issue_comment:
    types: [created]

permissions: read-all  # default read; writes scoped to job below

jobs:
  assignment-helper:
    permissions:
      issues: write
    uses: kubestellar/infra/.github/workflows/reusable-assignment-helper.yml@main
