name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    uses: kubestellar/infra/.github/workflows/reusable-stale.yml@9a15d65135864435badfb9293251e8701b562899  # main
    secrets: inherit
